Commit

diff --git a/.github/workflows/java-build-selfhosted-scanning_v1.yml b/.github/workflows/java-build-selfhosted-scanning_v1.yml
--- a/.github/workflows/java-build-selfhosted-scanning_v1.yml
+++ b/.github/workflows/java-build-selfhosted-scanning_v1.yml
@@ -25,7 +25,7 @@ env:
 jobs:
     Trivy:
       name: Trivy
-      runs-on: ubuntu-22.04 ##### it fails on self hosted runners and aws runners due to certificate checks. 
+      runs-on: ubuntu-latest ##### it fails on self hosted runners and aws runners due to certificate checks. 
       permissions:
         id-token: write # This is required for requesting the JWT for OIDC auth to AWS
         contents: read  # Required for checkout
@@ -116,120 +116,120 @@ jobs:
       #     if grep -q "CRITICAL\|HIGH" trivy-report.txt; then
       #       echo "Vulnerabilities detected!" && exit 1
       #     fi
-    # webgoat-semgrep-scan:
-    #   name: Run Semgrep and Generate HTML
-    #   runs-on: ubuntu-latest
+    webgoat-semgrep-scan:
+      name: Run Semgrep and Generate HTML
+      runs-on: ubuntu-latest
 
-    #   steps:
-    #     # Step 1: Check out the repository source code
-    #     - name: Checkout Code
-    #       uses: actions/checkout@v4
+      steps:
+        # Step 1: Check out the repository source code
+        - name: Checkout Code
+          uses: actions/checkout@v4
 
-    #     # Step 2: Set up Python environment
-    #     - name: Set up Python
-    #       uses: actions/setup-python@v5
-    #       with:
-    #         python-state: '3.11'
+        # Step 2: Set up Python environment
+        - name: Set up Python
+          uses: actions/setup-python@v5
+          with:
+            python-state: '3.11'
 
-    #     # # Step 3: Install Semgrep and the semgrep2html converter
-    #     - name: Install Dependencies
-    #       run: |
-    #         pip install semgrep
-    #         pip3 install jinja2
+        # # Step 3: Install Semgrep and the semgrep2html converter
+        - name: Install Dependencies
+          run: |
+            pip install semgrep
+            pip3 install jinja2
             
-    #     # # Step 3: Build App 
-    #     -   name: Set up JDK
-    #         uses: ./webgoat/.github/actions/java-setup
-    #         with:
-    #             cache: 'maven'
-    #     -   name: Build with Maven
-    #         run: cd webgoat && mvn clean install -DskipTests --no-transfer-progress verify
+        # # Step 3: Build App 
+        -   name: Set up JDK
+            uses: ./webgoat/.github/actions/java-setup
+            with:
+                cache: 'maven'
+        -   name: Build with Maven
+            run: cd webgoat && mvn clean install -DskipTests --no-transfer-progress verify
 
-    #     # # Step 4: Run Semgrep scan and force it to export JSON
-    #     # The '|| true' ensures the pipeline doesn't break instantly if vulnerabilities are found,
-    #     # allowing the HTML generation step to actually execute.
-    #     - name: Execute Semgrep Scan Webgoat
-    #       run: |
-    #         semgrep scan --config=auto ./webgoat/src --json --output=semgrep-results.json || true
+        # # Step 4: Run Semgrep scan and force it to export JSON
+        # The '|| true' ensures the pipeline doesn't break instantly if vulnerabilities are found,
+        # allowing the HTML generation step to actually execute.
+        - name: Execute Semgrep Scan Webgoat
+          run: |
+            semgrep scan --config=auto ./webgoat/src --json --output=semgrep-results.json || true
 
-    #   # 4. Run Semgrep with Supply Chain enabled
-    #     - name: Run Semgrep CI
-    #       env:
-    #         SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
-    #       run: |
-    #         # --allow-local-builds lets Semgrep query Maven for the full dependency tree
-    #         semgrep ci --allow-local-builds --include=webgoat --json --output=semgrep-web-results.json || true
+      # 4. Run Semgrep with Supply Chain enabled
+        - name: Run Semgrep CI
+          env:
+            SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
+          run: |
+            # --allow-local-builds lets Semgrep query Maven for the full dependency tree
+            semgrep ci --allow-local-builds --include=webgoat --json --output=semgrep-web-results.json || true
               
-    #     # # Step 5: Convert the JSON payload into a visual HTML dashboard
-    #     - name: Generate HTML Report Webgoat
-    #       run: |
-    #         python3 trivy/parse-semgrep.py --input semgrep-results.json --output semgrep-report.html --project-name "Webgoat" --only INFO,WARNING,ERROR
-    #         python3 trivy/parse-semgrep.py --input semgrep-web-results.json --output webgoat-web-semgrep-report.html --project-name "Webgoat" --only INFO,WARNING,ERROR
-    #       #            semgrep2html --input semgrep-results.json --output semgrep-report.html
+        # # Step 5: Convert the JSON payload into a visual HTML dashboard
+        - name: Generate HTML Report Webgoat
+          run: |
+            python3 trivy/parse-semgrep.py --input semgrep-results.json --output semgrep-report.html --project-name "Webgoat" --only INFO,WARNING,ERROR
+            python3 trivy/parse-semgrep.py --input semgrep-web-results.json --output webgoat-web-semgrep-report.html --project-name "Webgoat" --only INFO,WARNING,ERROR
+          #            semgrep2html --input semgrep-results.json --output semgrep-report.html
 
-    #     # Step 6: Upload the generated HTML file to GitHub Actions artifacts
-    #     - name: Upload HTML Report Artifact Webgoat
-    #       uses: actions/upload-artifact@v4
-    #       with:
-    #         name: webgoat-semgrep-security-report
-    #         path: semgrep-report.html
-    #         retention-days: 30
-    #     - name: Upload HTML Report Artifact Webgoat
-    #       uses: actions/upload-artifact@v4
-    #       with:
-    #         name: webgoat-web-semgrep-security-report
-    #         path: webgoat-web-semgrep-report.html
-    #         retention-days: 30
-    # juiceshop-semgrep-scan:
-    #   name: Run Semgrep and Generate HTML
-    #   runs-on: ubuntu-latest
+        # Step 6: Upload the generated HTML file to GitHub Actions artifacts
+        - name: Upload HTML Report Artifact Webgoat
+          uses: actions/upload-artifact@v4
+          with:
+            name: webgoat-semgrep-security-report
+            path: semgrep-report.html
+            retention-days: 30
+        - name: Upload HTML Report Artifact Webgoat
+          uses: actions/upload-artifact@v4
+          with:
+            name: webgoat-web-semgrep-security-report
+            path: webgoat-web-semgrep-report.html
+            retention-days: 30
+    juiceshop-semgrep-scan:
+      name: Run Semgrep and Generate HTML
+      runs-on: ubuntu-latest
 
-    #   steps:
-    #     # Step 1: Check out the repository source code
-    #     - name: Checkout Code
-    #       uses: actions/checkout@v4
+      steps:
+        # Step 1: Check out the repository source code
+        - name: Checkout Code
+          uses: actions/checkout@v4
 
-    #     # Step 2: Set up Python environment
-    #     - name: Set up Python
-    #       uses: actions/setup-python@v5
-    #       with:
-    #         python-state: '3.11'
+        # Step 2: Set up Python environment
+        - name: Set up Python
+          uses: actions/setup-python@v5
+          with:
+            python-state: '3.11'
 
-    #     # # Step 3: Install Semgrep and the semgrep2html converter
-    #     - name: Install Dependencies
-    #       run: |
-    #         pip install semgrep
-    #         pip3 install jinja2
+        # # Step 3: Install Semgrep and the semgrep2html converter
+        - name: Install Dependencies
+          run: |
+            pip install semgrep
+            pip3 install jinja2
             
-    #     - name: "Check out Git repository"
-    #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
-    #     - name: "Use Node.js 24"
-    #       uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af #v4.1.0
-    #       with:
-    #         node-version: 24
-    #     - name: "Install application"
-    #       run: cd juice_shop && npm install
+        - name: "Check out Git repository"
+          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
+        - name: "Use Node.js 24"
+          uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af #v4.1.0
+          with:
+            node-version: 24
+        - name: "Install application"
+          run: cd juice_shop && npm install
           
-    #     # # Step 4: Run Semgrep scan and force it to export JSON
-    #     # The '|| true' ensures the pipeline doesn't break instantly if vulnerabilities are found,
-    #     # allowing the HTML generation step to actually execute.
-    #     - name: Execute Semgrep Scan 
-    #       run: |
-    #         semgrep scan --config=auto ./juice_shop --json --output=semgrep-results.json || true
+        # # Step 4: Run Semgrep scan and force it to export JSON
+        # The '|| true' ensures the pipeline doesn't break instantly if vulnerabilities are found,
+        # allowing the HTML generation step to actually execute.
+        - name: Execute Semgrep Scan 
+          run: |
+            semgrep scan --config=auto ./juice_shop --json --output=semgrep-results.json || true
 
-    #     # # Step 5: Convert the JSON payload into a visual HTML dashboard
-    #     - name: Generate HTML Report 
-    #       run: |
-    #         python3 trivy/parse-semgrep.py --input semgrep-results.json --output juiceshop-semgrep-report.html --project-name "JuiceShop" --only INFO,WARNING,ERROR
-    #       #            semgrep2html --input semgrep-results.json --output semgrep-report.html
+        # # Step 5: Convert the JSON payload into a visual HTML dashboard
+        - name: Generate HTML Report 
+          run: |
+            python3 trivy/parse-semgrep.py --input semgrep-results.json --output juiceshop-semgrep-report.html --project-name "JuiceShop" --only INFO,WARNING,ERROR
+          #            semgrep2html --input semgrep-results.json --output semgrep-report.html
 
-    #     # Step 6: Upload the generated HTML file to GitHub Actions artifacts
-    #     - name: Upload HTML Report Artifact 
-    #       uses: actions/upload-artifact@v4
-    #       with:
-    #         name: juiceshop-semgrep-security-report
-    #         path: juiceshop-semgrep-report.html
-    #         retention-days: 30
+        # Step 6: Upload the generated HTML file to GitHub Actions artifacts
+        - name: Upload HTML Report Artifact 
+          uses: actions/upload-artifact@v4
+          with:
+            name: juiceshop-semgrep-security-report
+            path: juiceshop-semgrep-report.html
+            retention-days: 30
  
 
 
